// Code generated by ogen, DO NOT EDIT.

package ogen

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// CreateMailing implements createMailing operation.
//
// Создать рассылку.
//
// POST /mailings
func (UnimplementedHandler) CreateMailing(ctx context.Context, req *CreateMailingRequest) (r CreateMailingRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteMailing implements deleteMailing operation.
//
// Удалить рассылку.
//
// DELETE /mailings/{mailingID}
func (UnimplementedHandler) DeleteMailing(ctx context.Context, params DeleteMailingParams) (r DeleteMailingRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetMailing implements getMailing operation.
//
// Получить рассылку.
//
// GET /mailings/{mailingID}
func (UnimplementedHandler) GetMailing(ctx context.Context, params GetMailingParams) (r GetMailingRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListMailings implements listMailings operation.
//
// Получить список рассылок.
//
// GET /mailings
func (UnimplementedHandler) ListMailings(ctx context.Context, params ListMailingsParams) (r *MailingList, _ error) {
	return r, ht.ErrNotImplemented
}

// QueueMailing implements queueMailing operation.
//
// Создаёт новый запуск рассылки и задачи доставки для
// подходящих получателей. Допустимые исходные
// состояния: `draft` и `stopped`.
//
// POST /mailings/{mailingID}/queue
func (UnimplementedHandler) QueueMailing(ctx context.Context, params QueueMailingParams) (r QueueMailingRes, _ error) {
	return r, ht.ErrNotImplemented
}

// StopMailing implements stopMailing operation.
//
// Переводит рассылку в состояние `stopped`. Допустимые
// исходные состояния: `queued`, `running`, `paused`.
//
// POST /mailings/{mailingID}/stop
func (UnimplementedHandler) StopMailing(ctx context.Context, params StopMailingParams) (r StopMailingRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateMailing implements updateMailing operation.
//
// Изменить рассылку.
//
// PATCH /mailings/{mailingID}
func (UnimplementedHandler) UpdateMailing(ctx context.Context, req *UpdateMailingRequest, params UpdateMailingParams) (r UpdateMailingRes, _ error) {
	return r, ht.ErrNotImplemented
}
