// Code generated by ogen, DO NOT EDIT.

package ogen

import (
	"net/url"
	"time"

	"github.com/go-faster/errors"
	"github.com/google/uuid"
)

type CreateMailingBadRequest Problem

func (*CreateMailingBadRequest) createMailingRes() {}

type CreateMailingInternalServerError Problem

func (*CreateMailingInternalServerError) createMailingRes() {}

// Ref: #/components/schemas/CreateMailingRequest
type CreateMailingRequest struct {
	Name                  string               `json:"name"`
	MessageText           string               `json:"messageText"`
	SendMode              OptMailingSendMode   `json:"sendMode"`
	RepeatMode            OptMailingRepeatMode `json:"repeatMode"`
	RoundDelaySeconds     OptInt32             `json:"roundDelaySeconds"`
	RecipientDelaySeconds OptInt32             `json:"recipientDelaySeconds"`
	PostJoinDelaySeconds  OptInt32             `json:"postJoinDelaySeconds"`
	PreflightCheck        OptBool              `json:"preflightCheck"`
	AccountID             uuid.UUID            `json:"accountID"`
	Recipients            []MailingRecipient   `json:"recipients"`
	Schedule              OptSchedule          `json:"schedule"`
}

// GetName returns the value of Name.
func (s *CreateMailingRequest) GetName() string {
	return s.Name
}

// GetMessageText returns the value of MessageText.
func (s *CreateMailingRequest) GetMessageText() string {
	return s.MessageText
}

// GetSendMode returns the value of SendMode.
func (s *CreateMailingRequest) GetSendMode() OptMailingSendMode {
	return s.SendMode
}

// GetRepeatMode returns the value of RepeatMode.
func (s *CreateMailingRequest) GetRepeatMode() OptMailingRepeatMode {
	return s.RepeatMode
}

// GetRoundDelaySeconds returns the value of RoundDelaySeconds.
func (s *CreateMailingRequest) GetRoundDelaySeconds() OptInt32 {
	return s.RoundDelaySeconds
}

// GetRecipientDelaySeconds returns the value of RecipientDelaySeconds.
func (s *CreateMailingRequest) GetRecipientDelaySeconds() OptInt32 {
	return s.RecipientDelaySeconds
}

// GetPostJoinDelaySeconds returns the value of PostJoinDelaySeconds.
func (s *CreateMailingRequest) GetPostJoinDelaySeconds() OptInt32 {
	return s.PostJoinDelaySeconds
}

// GetPreflightCheck returns the value of PreflightCheck.
func (s *CreateMailingRequest) GetPreflightCheck() OptBool {
	return s.PreflightCheck
}

// GetAccountID returns the value of AccountID.
func (s *CreateMailingRequest) GetAccountID() uuid.UUID {
	return s.AccountID
}

// GetRecipients returns the value of Recipients.
func (s *CreateMailingRequest) GetRecipients() []MailingRecipient {
	return s.Recipients
}

// GetSchedule returns the value of Schedule.
func (s *CreateMailingRequest) GetSchedule() OptSchedule {
	return s.Schedule
}

// SetName sets the value of Name.
func (s *CreateMailingRequest) SetName(val string) {
	s.Name = val
}

// SetMessageText sets the value of MessageText.
func (s *CreateMailingRequest) SetMessageText(val string) {
	s.MessageText = val
}

// SetSendMode sets the value of SendMode.
func (s *CreateMailingRequest) SetSendMode(val OptMailingSendMode) {
	s.SendMode = val
}

// SetRepeatMode sets the value of RepeatMode.
func (s *CreateMailingRequest) SetRepeatMode(val OptMailingRepeatMode) {
	s.RepeatMode = val
}

// SetRoundDelaySeconds sets the value of RoundDelaySeconds.
func (s *CreateMailingRequest) SetRoundDelaySeconds(val OptInt32) {
	s.RoundDelaySeconds = val
}

// SetRecipientDelaySeconds sets the value of RecipientDelaySeconds.
func (s *CreateMailingRequest) SetRecipientDelaySeconds(val OptInt32) {
	s.RecipientDelaySeconds = val
}

// SetPostJoinDelaySeconds sets the value of PostJoinDelaySeconds.
func (s *CreateMailingRequest) SetPostJoinDelaySeconds(val OptInt32) {
	s.PostJoinDelaySeconds = val
}

// SetPreflightCheck sets the value of PreflightCheck.
func (s *CreateMailingRequest) SetPreflightCheck(val OptBool) {
	s.PreflightCheck = val
}

// SetAccountID sets the value of AccountID.
func (s *CreateMailingRequest) SetAccountID(val uuid.UUID) {
	s.AccountID = val
}

// SetRecipients sets the value of Recipients.
func (s *CreateMailingRequest) SetRecipients(val []MailingRecipient) {
	s.Recipients = val
}

// SetSchedule sets the value of Schedule.
func (s *CreateMailingRequest) SetSchedule(val OptSchedule) {
	s.Schedule = val
}

type DeleteMailingConflict Problem

func (*DeleteMailingConflict) deleteMailingRes() {}

type DeleteMailingInternalServerError Problem

func (*DeleteMailingInternalServerError) deleteMailingRes() {}

// DeleteMailingNoContent is response for DeleteMailing operation.
type DeleteMailingNoContent struct{}

func (*DeleteMailingNoContent) deleteMailingRes() {}

type DeleteMailingNotFound Problem

func (*DeleteMailingNotFound) deleteMailingRes() {}

type GetMailingInternalServerError Problem

func (*GetMailingInternalServerError) getMailingRes() {}

type GetMailingNotFound Problem

func (*GetMailingNotFound) getMailingRes() {}

// Ref: #/components/schemas/Mailing
type Mailing struct {
	ID                    uuid.UUID          `json:"id"`
	Name                  string             `json:"name"`
	MessageText           string             `json:"messageText"`
	Status                MailingStatus      `json:"status"`
	SendMode              MailingSendMode    `json:"sendMode"`
	RepeatMode            MailingRepeatMode  `json:"repeatMode"`
	RoundDelaySeconds     int32              `json:"roundDelaySeconds"`
	RecipientDelaySeconds int32              `json:"recipientDelaySeconds"`
	PostJoinDelaySeconds  int32              `json:"postJoinDelaySeconds"`
	PreflightCheck        bool               `json:"preflightCheck"`
	AccountID             uuid.UUID          `json:"accountID"`
	Recipients            []MailingRecipient `json:"recipients"`
	Schedule              Schedule           `json:"schedule"`
	CreatedAt             time.Time          `json:"createdAt"`
	UpdatedAt             time.Time          `json:"updatedAt"`
}

// GetID returns the value of ID.
func (s *Mailing) GetID() uuid.UUID {
	return s.ID
}

// GetName returns the value of Name.
func (s *Mailing) GetName() string {
	return s.Name
}

// GetMessageText returns the value of MessageText.
func (s *Mailing) GetMessageText() string {
	return s.MessageText
}

// GetStatus returns the value of Status.
func (s *Mailing) GetStatus() MailingStatus {
	return s.Status
}

// GetSendMode returns the value of SendMode.
func (s *Mailing) GetSendMode() MailingSendMode {
	return s.SendMode
}

// GetRepeatMode returns the value of RepeatMode.
func (s *Mailing) GetRepeatMode() MailingRepeatMode {
	return s.RepeatMode
}

// GetRoundDelaySeconds returns the value of RoundDelaySeconds.
func (s *Mailing) GetRoundDelaySeconds() int32 {
	return s.RoundDelaySeconds
}

// GetRecipientDelaySeconds returns the value of RecipientDelaySeconds.
func (s *Mailing) GetRecipientDelaySeconds() int32 {
	return s.RecipientDelaySeconds
}

// GetPostJoinDelaySeconds returns the value of PostJoinDelaySeconds.
func (s *Mailing) GetPostJoinDelaySeconds() int32 {
	return s.PostJoinDelaySeconds
}

// GetPreflightCheck returns the value of PreflightCheck.
func (s *Mailing) GetPreflightCheck() bool {
	return s.PreflightCheck
}

// GetAccountID returns the value of AccountID.
func (s *Mailing) GetAccountID() uuid.UUID {
	return s.AccountID
}

// GetRecipients returns the value of Recipients.
func (s *Mailing) GetRecipients() []MailingRecipient {
	return s.Recipients
}

// GetSchedule returns the value of Schedule.
func (s *Mailing) GetSchedule() Schedule {
	return s.Schedule
}

// GetCreatedAt returns the value of CreatedAt.
func (s *Mailing) GetCreatedAt() time.Time {
	return s.CreatedAt
}

// GetUpdatedAt returns the value of UpdatedAt.
func (s *Mailing) GetUpdatedAt() time.Time {
	return s.UpdatedAt
}

// SetID sets the value of ID.
func (s *Mailing) SetID(val uuid.UUID) {
	s.ID = val
}

// SetName sets the value of Name.
func (s *Mailing) SetName(val string) {
	s.Name = val
}

// SetMessageText sets the value of MessageText.
func (s *Mailing) SetMessageText(val string) {
	s.MessageText = val
}

// SetStatus sets the value of Status.
func (s *Mailing) SetStatus(val MailingStatus) {
	s.Status = val
}

// SetSendMode sets the value of SendMode.
func (s *Mailing) SetSendMode(val MailingSendMode) {
	s.SendMode = val
}

// SetRepeatMode sets the value of RepeatMode.
func (s *Mailing) SetRepeatMode(val MailingRepeatMode) {
	s.RepeatMode = val
}

// SetRoundDelaySeconds sets the value of RoundDelaySeconds.
func (s *Mailing) SetRoundDelaySeconds(val int32) {
	s.RoundDelaySeconds = val
}

// SetRecipientDelaySeconds sets the value of RecipientDelaySeconds.
func (s *Mailing) SetRecipientDelaySeconds(val int32) {
	s.RecipientDelaySeconds = val
}

// SetPostJoinDelaySeconds sets the value of PostJoinDelaySeconds.
func (s *Mailing) SetPostJoinDelaySeconds(val int32) {
	s.PostJoinDelaySeconds = val
}

// SetPreflightCheck sets the value of PreflightCheck.
func (s *Mailing) SetPreflightCheck(val bool) {
	s.PreflightCheck = val
}

// SetAccountID sets the value of AccountID.
func (s *Mailing) SetAccountID(val uuid.UUID) {
	s.AccountID = val
}

// SetRecipients sets the value of Recipients.
func (s *Mailing) SetRecipients(val []MailingRecipient) {
	s.Recipients = val
}

// SetSchedule sets the value of Schedule.
func (s *Mailing) SetSchedule(val Schedule) {
	s.Schedule = val
}

// SetCreatedAt sets the value of CreatedAt.
func (s *Mailing) SetCreatedAt(val time.Time) {
	s.CreatedAt = val
}

// SetUpdatedAt sets the value of UpdatedAt.
func (s *Mailing) SetUpdatedAt(val time.Time) {
	s.UpdatedAt = val
}

func (*Mailing) getMailingRes()    {}
func (*Mailing) updateMailingRes() {}

// MailingHeaders wraps Mailing with response headers.
type MailingHeaders struct {
	Location string
	Response Mailing
}

// GetLocation returns the value of Location.
func (s *MailingHeaders) GetLocation() string {
	return s.Location
}

// GetResponse returns the value of Response.
func (s *MailingHeaders) GetResponse() Mailing {
	return s.Response
}

// SetLocation sets the value of Location.
func (s *MailingHeaders) SetLocation(val string) {
	s.Location = val
}

// SetResponse sets the value of Response.
func (s *MailingHeaders) SetResponse(val Mailing) {
	s.Response = val
}

func (*MailingHeaders) createMailingRes() {}

// Ref: #/components/schemas/MailingList
type MailingList struct {
	Items []Mailing `json:"items"`
	Total int64     `json:"total"`
}

// GetItems returns the value of Items.
func (s *MailingList) GetItems() []Mailing {
	return s.Items
}

// GetTotal returns the value of Total.
func (s *MailingList) GetTotal() int64 {
	return s.Total
}

// SetItems sets the value of Items.
func (s *MailingList) SetItems(val []Mailing) {
	s.Items = val
}

// SetTotal sets the value of Total.
func (s *MailingList) SetTotal(val int64) {
	s.Total = val
}

// Ref: #/components/schemas/MailingRecipient
// MailingRecipient represents sum type.
type MailingRecipient struct {
	// Type selects the active sum variant, switch on this field.
	Type                   MailingRecipientType
	SharedDialogRecipient  SharedDialogRecipient
	PrivateDialogRecipient PrivateDialogRecipient
}

// MailingRecipientType is oneOf type of MailingRecipient.
type MailingRecipientType string

// Possible values for MailingRecipientType.
const (
	SharedDialogRecipientMailingRecipient  MailingRecipientType = "SharedDialogRecipient"
	PrivateDialogRecipientMailingRecipient MailingRecipientType = "PrivateDialogRecipient"
)

// IsSharedDialogRecipient reports whether MailingRecipient is SharedDialogRecipient.
func (s MailingRecipient) IsSharedDialogRecipient() bool {
	return s.Type == SharedDialogRecipientMailingRecipient
}

// IsPrivateDialogRecipient reports whether MailingRecipient is PrivateDialogRecipient.
func (s MailingRecipient) IsPrivateDialogRecipient() bool {
	return s.Type == PrivateDialogRecipientMailingRecipient
}

// SetSharedDialogRecipient sets MailingRecipient to SharedDialogRecipient.
func (s *MailingRecipient) SetSharedDialogRecipient(v SharedDialogRecipient) {
	s.Type = SharedDialogRecipientMailingRecipient
	s.SharedDialogRecipient = v
}

// GetSharedDialogRecipient returns SharedDialogRecipient and true boolean if MailingRecipient is SharedDialogRecipient.
func (s MailingRecipient) GetSharedDialogRecipient() (v SharedDialogRecipient, ok bool) {
	if !s.IsSharedDialogRecipient() {
		return v, false
	}
	return s.SharedDialogRecipient, true
}

// NewSharedDialogRecipientMailingRecipient returns new MailingRecipient from SharedDialogRecipient.
func NewSharedDialogRecipientMailingRecipient(v SharedDialogRecipient) MailingRecipient {
	var s MailingRecipient
	s.SetSharedDialogRecipient(v)
	return s
}

// SetPrivateDialogRecipient sets MailingRecipient to PrivateDialogRecipient.
func (s *MailingRecipient) SetPrivateDialogRecipient(v PrivateDialogRecipient) {
	s.Type = PrivateDialogRecipientMailingRecipient
	s.PrivateDialogRecipient = v
}

// GetPrivateDialogRecipient returns PrivateDialogRecipient and true boolean if MailingRecipient is PrivateDialogRecipient.
func (s MailingRecipient) GetPrivateDialogRecipient() (v PrivateDialogRecipient, ok bool) {
	if !s.IsPrivateDialogRecipient() {
		return v, false
	}
	return s.PrivateDialogRecipient, true
}

// NewPrivateDialogRecipientMailingRecipient returns new MailingRecipient from PrivateDialogRecipient.
func NewPrivateDialogRecipientMailingRecipient(v PrivateDialogRecipient) MailingRecipient {
	var s MailingRecipient
	s.SetPrivateDialogRecipient(v)
	return s
}

// Ref: #/components/schemas/MailingRepeatMode
type MailingRepeatMode string

const (
	MailingRepeatModeOnce   MailingRepeatMode = "once"
	MailingRepeatModeRounds MailingRepeatMode = "rounds"
)

// AllValues returns all MailingRepeatMode values.
func (MailingRepeatMode) AllValues() []MailingRepeatMode {
	return []MailingRepeatMode{
		MailingRepeatModeOnce,
		MailingRepeatModeRounds,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s MailingRepeatMode) MarshalText() ([]byte, error) {
	switch s {
	case MailingRepeatModeOnce:
		return []byte(s), nil
	case MailingRepeatModeRounds:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *MailingRepeatMode) UnmarshalText(data []byte) error {
	switch MailingRepeatMode(data) {
	case MailingRepeatModeOnce:
		*s = MailingRepeatModeOnce
		return nil
	case MailingRepeatModeRounds:
		*s = MailingRepeatModeRounds
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Ref: #/components/schemas/MailingSendMode
type MailingSendMode string

const (
	MailingSendModeSequential MailingSendMode = "sequential"
	MailingSendModeParallel   MailingSendMode = "parallel"
)

// AllValues returns all MailingSendMode values.
func (MailingSendMode) AllValues() []MailingSendMode {
	return []MailingSendMode{
		MailingSendModeSequential,
		MailingSendModeParallel,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s MailingSendMode) MarshalText() ([]byte, error) {
	switch s {
	case MailingSendModeSequential:
		return []byte(s), nil
	case MailingSendModeParallel:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *MailingSendMode) UnmarshalText(data []byte) error {
	switch MailingSendMode(data) {
	case MailingSendModeSequential:
		*s = MailingSendModeSequential
		return nil
	case MailingSendModeParallel:
		*s = MailingSendModeParallel
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Ref: #/components/schemas/MailingStatus
type MailingStatus string

const (
	MailingStatusDraft     MailingStatus = "draft"
	MailingStatusQueued    MailingStatus = "queued"
	MailingStatusRunning   MailingStatus = "running"
	MailingStatusPaused    MailingStatus = "paused"
	MailingStatusStopped   MailingStatus = "stopped"
	MailingStatusCompleted MailingStatus = "completed"
	MailingStatusFailed    MailingStatus = "failed"
)

// AllValues returns all MailingStatus values.
func (MailingStatus) AllValues() []MailingStatus {
	return []MailingStatus{
		MailingStatusDraft,
		MailingStatusQueued,
		MailingStatusRunning,
		MailingStatusPaused,
		MailingStatusStopped,
		MailingStatusCompleted,
		MailingStatusFailed,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s MailingStatus) MarshalText() ([]byte, error) {
	switch s {
	case MailingStatusDraft:
		return []byte(s), nil
	case MailingStatusQueued:
		return []byte(s), nil
	case MailingStatusRunning:
		return []byte(s), nil
	case MailingStatusPaused:
		return []byte(s), nil
	case MailingStatusStopped:
		return []byte(s), nil
	case MailingStatusCompleted:
		return []byte(s), nil
	case MailingStatusFailed:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *MailingStatus) UnmarshalText(data []byte) error {
	switch MailingStatus(data) {
	case MailingStatusDraft:
		*s = MailingStatusDraft
		return nil
	case MailingStatusQueued:
		*s = MailingStatusQueued
		return nil
	case MailingStatusRunning:
		*s = MailingStatusRunning
		return nil
	case MailingStatusPaused:
		*s = MailingStatusPaused
		return nil
	case MailingStatusStopped:
		*s = MailingStatusStopped
		return nil
	case MailingStatusCompleted:
		*s = MailingStatusCompleted
		return nil
	case MailingStatusFailed:
		*s = MailingStatusFailed
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// NewOptBool returns new OptBool with value set to v.
func NewOptBool(v bool) OptBool {
	return OptBool{
		Value: v,
		Set:   true,
	}
}

// OptBool is optional bool.
type OptBool struct {
	Value bool
	Set   bool
}

// IsSet returns true if OptBool was set.
func (o OptBool) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptBool) Reset() {
	var v bool
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptBool) SetTo(v bool) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptBool) Get() (v bool, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptBool) Or(d bool) bool {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptInt32 returns new OptInt32 with value set to v.
func NewOptInt32(v int32) OptInt32 {
	return OptInt32{
		Value: v,
		Set:   true,
	}
}

// OptInt32 is optional int32.
type OptInt32 struct {
	Value int32
	Set   bool
}

// IsSet returns true if OptInt32 was set.
func (o OptInt32) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptInt32) Reset() {
	var v int32
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptInt32) SetTo(v int32) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptInt32) Get() (v int32, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptInt32) Or(d int32) int32 {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptMailingRepeatMode returns new OptMailingRepeatMode with value set to v.
func NewOptMailingRepeatMode(v MailingRepeatMode) OptMailingRepeatMode {
	return OptMailingRepeatMode{
		Value: v,
		Set:   true,
	}
}

// OptMailingRepeatMode is optional MailingRepeatMode.
type OptMailingRepeatMode struct {
	Value MailingRepeatMode
	Set   bool
}

// IsSet returns true if OptMailingRepeatMode was set.
func (o OptMailingRepeatMode) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptMailingRepeatMode) Reset() {
	var v MailingRepeatMode
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptMailingRepeatMode) SetTo(v MailingRepeatMode) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptMailingRepeatMode) Get() (v MailingRepeatMode, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptMailingRepeatMode) Or(d MailingRepeatMode) MailingRepeatMode {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptMailingSendMode returns new OptMailingSendMode with value set to v.
func NewOptMailingSendMode(v MailingSendMode) OptMailingSendMode {
	return OptMailingSendMode{
		Value: v,
		Set:   true,
	}
}

// OptMailingSendMode is optional MailingSendMode.
type OptMailingSendMode struct {
	Value MailingSendMode
	Set   bool
}

// IsSet returns true if OptMailingSendMode was set.
func (o OptMailingSendMode) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptMailingSendMode) Reset() {
	var v MailingSendMode
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptMailingSendMode) SetTo(v MailingSendMode) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptMailingSendMode) Get() (v MailingSendMode, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptMailingSendMode) Or(d MailingSendMode) MailingSendMode {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptMailingStatus returns new OptMailingStatus with value set to v.
func NewOptMailingStatus(v MailingStatus) OptMailingStatus {
	return OptMailingStatus{
		Value: v,
		Set:   true,
	}
}

// OptMailingStatus is optional MailingStatus.
type OptMailingStatus struct {
	Value MailingStatus
	Set   bool
}

// IsSet returns true if OptMailingStatus was set.
func (o OptMailingStatus) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptMailingStatus) Reset() {
	var v MailingStatus
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptMailingStatus) SetTo(v MailingStatus) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptMailingStatus) Get() (v MailingStatus, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptMailingStatus) Or(d MailingStatus) MailingStatus {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptNilDateTime returns new OptNilDateTime with value set to v.
func NewOptNilDateTime(v time.Time) OptNilDateTime {
	return OptNilDateTime{
		Value: v,
		Set:   true,
	}
}

// OptNilDateTime is optional nullable time.Time.
type OptNilDateTime struct {
	Value time.Time
	Set   bool
	Null  bool
}

// IsSet returns true if OptNilDateTime was set.
func (o OptNilDateTime) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptNilDateTime) Reset() {
	var v time.Time
	o.Value = v
	o.Set = false
	o.Null = false
}

// SetTo sets value to v.
func (o *OptNilDateTime) SetTo(v time.Time) {
	o.Set = true
	o.Null = false
	o.Value = v
}

// IsNull returns true if value is Null.
func (o OptNilDateTime) IsNull() bool { return o.Null }

// SetToNull sets value to null.
func (o *OptNilDateTime) SetToNull() {
	o.Set = true
	o.Null = true
	var v time.Time
	o.Value = v
}

// IsEmpty returns true if the field was omitted from the payload (not Set and not Null).
func (o OptNilDateTime) IsEmpty() bool {
	return !o.Set && !o.Null
}

// Get returns value and boolean that denotes whether value was set.
func (o OptNilDateTime) Get() (v time.Time, ok bool) {
	if o.Null {
		return v, false
	}
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptNilDateTime) Or(d time.Time) time.Time {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptNilTime returns new OptNilTime with value set to v.
func NewOptNilTime(v time.Time) OptNilTime {
	return OptNilTime{
		Value: v,
		Set:   true,
	}
}

// OptNilTime is optional nullable time.Time.
type OptNilTime struct {
	Value time.Time
	Set   bool
	Null  bool
}

// IsSet returns true if OptNilTime was set.
func (o OptNilTime) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptNilTime) Reset() {
	var v time.Time
	o.Value = v
	o.Set = false
	o.Null = false
}

// SetTo sets value to v.
func (o *OptNilTime) SetTo(v time.Time) {
	o.Set = true
	o.Null = false
	o.Value = v
}

// IsNull returns true if value is Null.
func (o OptNilTime) IsNull() bool { return o.Null }

// SetToNull sets value to null.
func (o *OptNilTime) SetToNull() {
	o.Set = true
	o.Null = true
	var v time.Time
	o.Value = v
}

// IsEmpty returns true if the field was omitted from the payload (not Set and not Null).
func (o OptNilTime) IsEmpty() bool {
	return !o.Set && !o.Null
}

// Get returns value and boolean that denotes whether value was set.
func (o OptNilTime) Get() (v time.Time, ok bool) {
	if o.Null {
		return v, false
	}
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptNilTime) Or(d time.Time) time.Time {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptSchedule returns new OptSchedule with value set to v.
func NewOptSchedule(v Schedule) OptSchedule {
	return OptSchedule{
		Value: v,
		Set:   true,
	}
}

// OptSchedule is optional Schedule.
type OptSchedule struct {
	Value Schedule
	Set   bool
}

// IsSet returns true if OptSchedule was set.
func (o OptSchedule) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptSchedule) Reset() {
	var v Schedule
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptSchedule) SetTo(v Schedule) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptSchedule) Get() (v Schedule, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptSchedule) Or(d Schedule) Schedule {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptString returns new OptString with value set to v.
func NewOptString(v string) OptString {
	return OptString{
		Value: v,
		Set:   true,
	}
}

// OptString is optional string.
type OptString struct {
	Value string
	Set   bool
}

// IsSet returns true if OptString was set.
func (o OptString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptString) Reset() {
	var v string
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptString) SetTo(v string) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptString) Get() (v string, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptURI returns new OptURI with value set to v.
func NewOptURI(v url.URL) OptURI {
	return OptURI{
		Value: v,
		Set:   true,
	}
}

// OptURI is optional url.URL.
type OptURI struct {
	Value url.URL
	Set   bool
}

// IsSet returns true if OptURI was set.
func (o OptURI) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptURI) Reset() {
	var v url.URL
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptURI) SetTo(v url.URL) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptURI) Get() (v url.URL, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptURI) Or(d url.URL) url.URL {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptUUID returns new OptUUID with value set to v.
func NewOptUUID(v uuid.UUID) OptUUID {
	return OptUUID{
		Value: v,
		Set:   true,
	}
}

// OptUUID is optional uuid.UUID.
type OptUUID struct {
	Value uuid.UUID
	Set   bool
}

// IsSet returns true if OptUUID was set.
func (o OptUUID) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptUUID) Reset() {
	var v uuid.UUID
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptUUID) SetTo(v uuid.UUID) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptUUID) Get() (v uuid.UUID, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptUUID) Or(d uuid.UUID) uuid.UUID {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// Ref: #/components/schemas/PeerType
type PeerType string

const (
	PeerTypeUser    PeerType = "user"
	PeerTypeChat    PeerType = "chat"
	PeerTypeChannel PeerType = "channel"
)

// AllValues returns all PeerType values.
func (PeerType) AllValues() []PeerType {
	return []PeerType{
		PeerTypeUser,
		PeerTypeChat,
		PeerTypeChannel,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s PeerType) MarshalText() ([]byte, error) {
	switch s {
	case PeerTypeUser:
		return []byte(s), nil
	case PeerTypeChat:
		return []byte(s), nil
	case PeerTypeChannel:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *PeerType) UnmarshalText(data []byte) error {
	switch PeerType(data) {
	case PeerTypeUser:
		*s = PeerTypeUser
		return nil
	case PeerTypeChat:
		*s = PeerTypeChat
		return nil
	case PeerTypeChannel:
		*s = PeerTypeChannel
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Ref: #/components/schemas/PrivateDialogRecipient
type PrivateDialogRecipient struct {
	PrivateAccountID uuid.UUID `json:"privateAccountID"`
	PeerType         PeerType  `json:"peerType"`
	PeerID           int64     `json:"peerID"`
}

// GetPrivateAccountID returns the value of PrivateAccountID.
func (s *PrivateDialogRecipient) GetPrivateAccountID() uuid.UUID {
	return s.PrivateAccountID
}

// GetPeerType returns the value of PeerType.
func (s *PrivateDialogRecipient) GetPeerType() PeerType {
	return s.PeerType
}

// GetPeerID returns the value of PeerID.
func (s *PrivateDialogRecipient) GetPeerID() int64 {
	return s.PeerID
}

// SetPrivateAccountID sets the value of PrivateAccountID.
func (s *PrivateDialogRecipient) SetPrivateAccountID(val uuid.UUID) {
	s.PrivateAccountID = val
}

// SetPeerType sets the value of PeerType.
func (s *PrivateDialogRecipient) SetPeerType(val PeerType) {
	s.PeerType = val
}

// SetPeerID sets the value of PeerID.
func (s *PrivateDialogRecipient) SetPeerID(val int64) {
	s.PeerID = val
}

// Ref: #/components/schemas/Problem
type Problem struct {
	Type     OptURI    `json:"type"`
	Title    string    `json:"title"`
	Status   int32     `json:"status"`
	Detail   OptString `json:"detail"`
	Instance OptString `json:"instance"`
}

// GetType returns the value of Type.
func (s *Problem) GetType() OptURI {
	return s.Type
}

// GetTitle returns the value of Title.
func (s *Problem) GetTitle() string {
	return s.Title
}

// GetStatus returns the value of Status.
func (s *Problem) GetStatus() int32 {
	return s.Status
}

// GetDetail returns the value of Detail.
func (s *Problem) GetDetail() OptString {
	return s.Detail
}

// GetInstance returns the value of Instance.
func (s *Problem) GetInstance() OptString {
	return s.Instance
}

// SetType sets the value of Type.
func (s *Problem) SetType(val OptURI) {
	s.Type = val
}

// SetTitle sets the value of Title.
func (s *Problem) SetTitle(val string) {
	s.Title = val
}

// SetStatus sets the value of Status.
func (s *Problem) SetStatus(val int32) {
	s.Status = val
}

// SetDetail sets the value of Detail.
func (s *Problem) SetDetail(val OptString) {
	s.Detail = val
}

// SetInstance sets the value of Instance.
func (s *Problem) SetInstance(val OptString) {
	s.Instance = val
}

type QueueMailingConflict Problem

func (*QueueMailingConflict) queueMailingRes() {}

type QueueMailingInternalServerError Problem

func (*QueueMailingInternalServerError) queueMailingRes() {}

// QueueMailingNoContent is response for QueueMailing operation.
type QueueMailingNoContent struct{}

func (*QueueMailingNoContent) queueMailingRes() {}

type QueueMailingNotFound Problem

func (*QueueMailingNotFound) queueMailingRes() {}

// Ref: #/components/schemas/Schedule
type Schedule struct {
	Mode       ScheduleMode   `json:"mode"`
	StartsAt   OptNilDateTime `json:"startsAt"`
	EndsAt     OptNilDateTime `json:"endsAt"`
	DailyUntil OptNilTime     `json:"dailyUntil"`
	Timezone   string         `json:"timezone"`
}

// GetMode returns the value of Mode.
func (s *Schedule) GetMode() ScheduleMode {
	return s.Mode
}

// GetStartsAt returns the value of StartsAt.
func (s *Schedule) GetStartsAt() OptNilDateTime {
	return s.StartsAt
}

// GetEndsAt returns the value of EndsAt.
func (s *Schedule) GetEndsAt() OptNilDateTime {
	return s.EndsAt
}

// GetDailyUntil returns the value of DailyUntil.
func (s *Schedule) GetDailyUntil() OptNilTime {
	return s.DailyUntil
}

// GetTimezone returns the value of Timezone.
func (s *Schedule) GetTimezone() string {
	return s.Timezone
}

// SetMode sets the value of Mode.
func (s *Schedule) SetMode(val ScheduleMode) {
	s.Mode = val
}

// SetStartsAt sets the value of StartsAt.
func (s *Schedule) SetStartsAt(val OptNilDateTime) {
	s.StartsAt = val
}

// SetEndsAt sets the value of EndsAt.
func (s *Schedule) SetEndsAt(val OptNilDateTime) {
	s.EndsAt = val
}

// SetDailyUntil sets the value of DailyUntil.
func (s *Schedule) SetDailyUntil(val OptNilTime) {
	s.DailyUntil = val
}

// SetTimezone sets the value of Timezone.
func (s *Schedule) SetTimezone(val string) {
	s.Timezone = val
}

// Ref: #/components/schemas/ScheduleMode
type ScheduleMode string

const (
	ScheduleModeAlways ScheduleMode = "always"
	ScheduleModeWindow ScheduleMode = "window"
)

// AllValues returns all ScheduleMode values.
func (ScheduleMode) AllValues() []ScheduleMode {
	return []ScheduleMode{
		ScheduleModeAlways,
		ScheduleModeWindow,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s ScheduleMode) MarshalText() ([]byte, error) {
	switch s {
	case ScheduleModeAlways:
		return []byte(s), nil
	case ScheduleModeWindow:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *ScheduleMode) UnmarshalText(data []byte) error {
	switch ScheduleMode(data) {
	case ScheduleModeAlways:
		*s = ScheduleModeAlways
		return nil
	case ScheduleModeWindow:
		*s = ScheduleModeWindow
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Ref: #/components/schemas/SharedDialogRecipient
type SharedDialogRecipient struct {
	SharedDialogID uuid.UUID `json:"sharedDialogID"`
}

// GetSharedDialogID returns the value of SharedDialogID.
func (s *SharedDialogRecipient) GetSharedDialogID() uuid.UUID {
	return s.SharedDialogID
}

// SetSharedDialogID sets the value of SharedDialogID.
func (s *SharedDialogRecipient) SetSharedDialogID(val uuid.UUID) {
	s.SharedDialogID = val
}

type StopMailingConflict Problem

func (*StopMailingConflict) stopMailingRes() {}

type StopMailingInternalServerError Problem

func (*StopMailingInternalServerError) stopMailingRes() {}

// StopMailingNoContent is response for StopMailing operation.
type StopMailingNoContent struct{}

func (*StopMailingNoContent) stopMailingRes() {}

type StopMailingNotFound Problem

func (*StopMailingNotFound) stopMailingRes() {}

type UpdateMailingBadRequest Problem

func (*UpdateMailingBadRequest) updateMailingRes() {}

type UpdateMailingConflict Problem

func (*UpdateMailingConflict) updateMailingRes() {}

type UpdateMailingInternalServerError Problem

func (*UpdateMailingInternalServerError) updateMailingRes() {}

type UpdateMailingNotFound Problem

func (*UpdateMailingNotFound) updateMailingRes() {}

// Ref: #/components/schemas/UpdateMailingRequest
type UpdateMailingRequest struct {
	Name                  OptString            `json:"name"`
	MessageText           OptString            `json:"messageText"`
	SendMode              OptMailingSendMode   `json:"sendMode"`
	RepeatMode            OptMailingRepeatMode `json:"repeatMode"`
	RoundDelaySeconds     OptInt32             `json:"roundDelaySeconds"`
	RecipientDelaySeconds OptInt32             `json:"recipientDelaySeconds"`
	PostJoinDelaySeconds  OptInt32             `json:"postJoinDelaySeconds"`
	PreflightCheck        OptBool              `json:"preflightCheck"`
	AccountID             OptUUID              `json:"accountID"`
	Recipients            []MailingRecipient   `json:"recipients"`
	Schedule              OptSchedule          `json:"schedule"`
}

// GetName returns the value of Name.
func (s *UpdateMailingRequest) GetName() OptString {
	return s.Name
}

// GetMessageText returns the value of MessageText.
func (s *UpdateMailingRequest) GetMessageText() OptString {
	return s.MessageText
}

// GetSendMode returns the value of SendMode.
func (s *UpdateMailingRequest) GetSendMode() OptMailingSendMode {
	return s.SendMode
}

// GetRepeatMode returns the value of RepeatMode.
func (s *UpdateMailingRequest) GetRepeatMode() OptMailingRepeatMode {
	return s.RepeatMode
}

// GetRoundDelaySeconds returns the value of RoundDelaySeconds.
func (s *UpdateMailingRequest) GetRoundDelaySeconds() OptInt32 {
	return s.RoundDelaySeconds
}

// GetRecipientDelaySeconds returns the value of RecipientDelaySeconds.
func (s *UpdateMailingRequest) GetRecipientDelaySeconds() OptInt32 {
	return s.RecipientDelaySeconds
}

// GetPostJoinDelaySeconds returns the value of PostJoinDelaySeconds.
func (s *UpdateMailingRequest) GetPostJoinDelaySeconds() OptInt32 {
	return s.PostJoinDelaySeconds
}

// GetPreflightCheck returns the value of PreflightCheck.
func (s *UpdateMailingRequest) GetPreflightCheck() OptBool {
	return s.PreflightCheck
}

// GetAccountID returns the value of AccountID.
func (s *UpdateMailingRequest) GetAccountID() OptUUID {
	return s.AccountID
}

// GetRecipients returns the value of Recipients.
func (s *UpdateMailingRequest) GetRecipients() []MailingRecipient {
	return s.Recipients
}

// GetSchedule returns the value of Schedule.
func (s *UpdateMailingRequest) GetSchedule() OptSchedule {
	return s.Schedule
}

// SetName sets the value of Name.
func (s *UpdateMailingRequest) SetName(val OptString) {
	s.Name = val
}

// SetMessageText sets the value of MessageText.
func (s *UpdateMailingRequest) SetMessageText(val OptString) {
	s.MessageText = val
}

// SetSendMode sets the value of SendMode.
func (s *UpdateMailingRequest) SetSendMode(val OptMailingSendMode) {
	s.SendMode = val
}

// SetRepeatMode sets the value of RepeatMode.
func (s *UpdateMailingRequest) SetRepeatMode(val OptMailingRepeatMode) {
	s.RepeatMode = val
}

// SetRoundDelaySeconds sets the value of RoundDelaySeconds.
func (s *UpdateMailingRequest) SetRoundDelaySeconds(val OptInt32) {
	s.RoundDelaySeconds = val
}

// SetRecipientDelaySeconds sets the value of RecipientDelaySeconds.
func (s *UpdateMailingRequest) SetRecipientDelaySeconds(val OptInt32) {
	s.RecipientDelaySeconds = val
}

// SetPostJoinDelaySeconds sets the value of PostJoinDelaySeconds.
func (s *UpdateMailingRequest) SetPostJoinDelaySeconds(val OptInt32) {
	s.PostJoinDelaySeconds = val
}

// SetPreflightCheck sets the value of PreflightCheck.
func (s *UpdateMailingRequest) SetPreflightCheck(val OptBool) {
	s.PreflightCheck = val
}

// SetAccountID sets the value of AccountID.
func (s *UpdateMailingRequest) SetAccountID(val OptUUID) {
	s.AccountID = val
}

// SetRecipients sets the value of Recipients.
func (s *UpdateMailingRequest) SetRecipients(val []MailingRecipient) {
	s.Recipients = val
}

// SetSchedule sets the value of Schedule.
func (s *UpdateMailingRequest) SetSchedule(val OptSchedule) {
	s.Schedule = val
}
