// Code generated by ogen, DO NOT EDIT.
package ogen

type CreateMailingRes interface {
	createMailingRes()
}

type DeleteMailingRes interface {
	deleteMailingRes()
}

type GetMailingRes interface {
	getMailingRes()
}

type QueueMailingRes interface {
	queueMailingRes()
}

type StopMailingRes interface {
	stopMailingRes()
}

type UpdateMailingRes interface {
	updateMailingRes()
}
