// Code generated by ogen, DO NOT EDIT.

package ogen

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// CreateMailing implements createMailing operation.
	//
	// Создать рассылку.
	//
	// POST /mailings
	CreateMailing(ctx context.Context, req *CreateMailingRequest) (CreateMailingRes, error)
	// DeleteMailing implements deleteMailing operation.
	//
	// Удалить рассылку.
	//
	// DELETE /mailings/{mailingID}
	DeleteMailing(ctx context.Context, params DeleteMailingParams) (DeleteMailingRes, error)
	// GetMailing implements getMailing operation.
	//
	// Получить рассылку.
	//
	// GET /mailings/{mailingID}
	GetMailing(ctx context.Context, params GetMailingParams) (GetMailingRes, error)
	// ListMailings implements listMailings operation.
	//
	// Получить список рассылок.
	//
	// GET /mailings
	ListMailings(ctx context.Context, params ListMailingsParams) (*MailingList, error)
	// QueueMailing implements queueMailing operation.
	//
	// Создаёт новый запуск рассылки и задачи доставки для
	// подходящих получателей. Допустимые исходные
	// состояния: `draft` и `stopped`.
	//
	// POST /mailings/{mailingID}/queue
	QueueMailing(ctx context.Context, params QueueMailingParams) (QueueMailingRes, error)
	// StopMailing implements stopMailing operation.
	//
	// Атомарно отменяет активный запуск и переводит
	// рассылку в состояние `stopped`. Ожидающие доставки
	// пропускаются и освобождают свои lease. Уже допущенные к
	// отправке доставки (`sending`) не изменяются, поэтому их
	// результат может быть сохранён после ответа. Повторная
	// остановка уже остановленной рассылки идемпотентно
	// возвращает `204`. Допустимые исходные состояния: `queued`,
	// `running`, `paused`, `stopped`.
	//
	// POST /mailings/{mailingID}/stop
	StopMailing(ctx context.Context, params StopMailingParams) (StopMailingRes, error)
	// UpdateMailing implements updateMailing operation.
	//
	// Изменить рассылку.
	//
	// PATCH /mailings/{mailingID}
	UpdateMailing(ctx context.Context, req *UpdateMailingRequest, params UpdateMailingParams) (UpdateMailingRes, error)
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h Handler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		baseServer: s,
	}, nil
}
