// Code generated by ogen, DO NOT EDIT.

package ogen

// OperationName is the ogen operation name
type OperationName = string

const (
	CreateMailingOperation OperationName = "CreateMailing"
	DeleteMailingOperation OperationName = "DeleteMailing"
	GetMailingOperation    OperationName = "GetMailing"
	ListMailingsOperation  OperationName = "ListMailings"
	QueueMailingOperation  OperationName = "QueueMailing"
	StopMailingOperation   OperationName = "StopMailing"
	UpdateMailingOperation OperationName = "UpdateMailing"
)
